# UI-only M3 layer. Every assignment, score, journey and event comes from Bunny Host.
$bunnyMotion=@{micro=150;content=220;morph=360;route=760;success=560;warning=2400;breath=3200}
$bunnyIcons['check']='M 20,6 L 9,17 L 4,12'
$bunnyOrbState='';$bunnyReplayAt=$null
function Set-BunnyMotionMode {
 $previous=$bunnyAnimate
 $script:bunnyAnimate=-not$SmokeTest-and[Windows.SystemParameters]::ClientAreaAnimation-and-not[Windows.SystemParameters]::HighContrast-and$bunnyPreferences.motion-eq'full'
 if($previous-ne$bunnyAnimate){$script:bunnyOrbState=''}
 if($bunnyAnimate-and-not$bunnyControls.ActivityDots.HasAnimatedProperties){$pulse=[Windows.Media.Animation.DoubleAnimation]::new(.35,1,[Windows.Duration]::new([TimeSpan]::FromMilliseconds($bunnyMotion.route)));$pulse.AutoReverse=$true;$pulse.RepeatBehavior=[Windows.Media.Animation.RepeatBehavior]::Forever;$bunnyControls.ActivityDots.BeginAnimation([Windows.UIElement]::OpacityProperty,$pulse)}
 if(-not$bunnyAnimate){$bunnyControls.ActivityDots.BeginAnimation([Windows.UIElement]::OpacityProperty,$null);$bunnyControls.ActivityDots.Opacity=0.8;$bunnyWindow.BeginAnimation([Windows.Window]::WidthProperty,$null);$bunnyWindow.BeginAnimation([Windows.Window]::HeightProperty,$null);$bunnyControls.Details.BeginAnimation([Windows.UIElement]::OpacityProperty,$null)}
}
function New-BunnyCaption([string]$Text,[string]$Ink='BunnyMuted') {
 $textBlock=[Windows.Controls.TextBlock]::new();$textBlock.Text=$Text;$textBlock.FontSize=11;$textBlock.TextWrapping='Wrap';Set-BunnyRef $textBlock ([Windows.Controls.TextBlock]::ForegroundProperty) $Ink;return $textBlock
}
function Add-BunnyMicroTelemetry($Panel,[switch]$CpuOnly) {
 $sample=@($bunnySnapshot.samples)|Select-Object -Last 1
 $sensors=@('CPU');if(-not$CpuOnly-and$sample.gpus.Count){$sensors+='GPU'}
 foreach($sensor in $sensors){$stack=[Windows.Controls.StackPanel]::new();$stack.Width=if($CpuOnly){40}else{76};$stack.Margin='4,0,4,0';$caption=New-BunnyCaption $sensor;[void]$stack.Children.Add($caption);$canvas=[Windows.Controls.Canvas]::new();$canvas.Height=14;$canvas.Width=$stack.Width;[void]$stack.Children.Add($canvas)
  $history=@($bunnySnapshot.samples|Select-Object -Last 20);$run=[Windows.Shapes.Polyline]::new();$run.StrokeThickness=1.2;Set-BunnyRef $run ([Windows.Shapes.Shape]::StrokeProperty) 'BunnyAccent';[void]$canvas.Children.Add($run)
  for($i=0;$i-lt$history.Count;$i++){$value=if($sensor-eq'CPU'){$history[$i].cpu.utilization}else{(@($history[$i].gpus|Where-Object name -eq $sample.gpus[0].name)|Select-Object -First 1).utilization};if($bunnyOnline-and$null-ne$value){$run.Points.Add([Windows.Point]::new($i*[double]$canvas.Width/[Math]::Max(1,$history.Count-1),13-([Math]::Min(100,[Math]::Max(0,[double]$value))/100)*12))}else{$run=[Windows.Shapes.Polyline]::new();$run.StrokeThickness=1.2;Set-BunnyRef $run ([Windows.Shapes.Shape]::StrokeProperty) 'BunnyAccent';[void]$canvas.Children.Add($run)}}
  $stack.ToolTip=$sensor+' utilization history from Host samples';[void]$Panel.Children.Add($stack)
 }
}
function New-BunnyTaskRow($Task) {
 $grid=[Windows.Controls.Grid]::new();foreach($width in @('44','*','64')){$column=[Windows.Controls.ColumnDefinition]::new();$column.Width=$width;[void]$grid.ColumnDefinitions.Add($column)}
 $tile=New-BunnyTile $Task.provider 28;$tile.VerticalAlignment='Center';[void]$grid.Children.Add($tile);$text=[Windows.Controls.StackPanel]::new();$text.Margin='8,8,8,8';[Windows.Controls.Grid]::SetColumn($text,1);[void]$text.Children.Add((New-BunnyCaption (Get-BunnyProviderName $Task.provider) 'BunnyText'));$detail=if($Task.latestEvent.type-match'thinking|reasoning'){'Working...'}elseif($Task.latestEvent.label){$Task.latestEvent.label}else{(Get-BunnyStateInfo $Task.state).Label};$caption=New-BunnyCaption $detail;$caption.TextWrapping='NoWrap';$caption.TextTrimming='CharacterEllipsis';[void]$text.Children.Add($caption);[void]$grid.Children.Add($text)
 $right=[Windows.Controls.StackPanel]::new();$right.VerticalAlignment='Center';[Windows.Controls.Grid]::SetColumn($right,2);[void]$right.Children.Add((New-BunnyCaption (Get-BunnyElapsed $Task)));$spark=[Windows.Shapes.Polyline]::new();$spark.Width=54;$spark.Height=16;$spark.StrokeThickness=1.2;Set-BunnyRef $spark ([Windows.Shapes.Shape]::StrokeProperty) 'BunnyAccent';$now=[DateTimeOffset]::Now.ToUnixTimeMilliseconds();$counts=@();for($i=0;$i-lt6;$i++){$counts+=@($bunnySnapshot.events|Where-Object {$_.taskId-eq$Task.id-and$_.type-like'agent.*'-and$_.type-notmatch'thinking|reasoning|output'-and$_.at-gt($now-30000+$i*5000)-and$_.at-le($now-25000+$i*5000)}).Count};$peak=[Math]::Max(1,($counts|Measure-Object -Maximum).Maximum);for($i=0;$i-lt6;$i++){$spark.Points.Add([Windows.Point]::new($i*10+2,15-$counts[$i]/$peak*12))};$spark.ToolTip='Recorded agent actions in the last 30 seconds';[void]$right.Children.Add($spark);[void]$grid.Children.Add($right);return $grid
}
function Draw-BunnyComparison {
 $panel=$bunnyControls.ProviderComparison;$panel.Children.Clear();$task=@($bunnySnapshot.tasks|Where-Object id -eq $bunnySelectedId)|Select-Object -First 1
 if(-not$task){return};[void]$panel.Children.Add((New-BunnyCaption 'COMPARE AGENTS - recorded route scores' 'BunnyText'))
 foreach($score in $task.decision.scores){$provider=@($bunnySnapshot.providers|Where-Object id -eq $score.provider)|Select-Object -First 1;$card=[Windows.Controls.StackPanel]::new();$card.Margin='0,12,0,0';[void]$card.Children.Add((New-BunnyCaption ((Get-BunnyProviderName $score.provider)+'  '+([double]$score.score).ToString('0.00')+'  '+$provider.availability.Replace('_',' ')) 'BunnyText'));$execution=if($score.provider-eq'ollama'-and$provider.current_model-match':cloud$'){'Cloud model'}else{$provider.local_or_cloud};$usage=if($score.provider-eq'ollama'){'No subscription quota'}elseif($provider.usageWindows.Count){@($provider.usageWindows|ForEach-Object {$_.label+': '+$_.usedPercent+'%'})-join'; '}else{'Usage unavailable'};[void]$card.Children.Add((New-BunnyCaption ($execution+' - '+$usage)));$history=@($bunnySnapshot.performance|Where-Object {$_.provider-eq$score.provider-and$_.taskType-eq$task.decision.task_type});$speed=if($null-ne$provider.latency_estimate_ms){([Math]::Round($provider.latency_estimate_ms/1000,1)).ToString()+'s observed'}else{'Unavailable'};[void]$card.Children.Add((New-BunnyCaption ('Speed: '+$speed+' - History: '+$(if($history.Count){[string]($history|Measure-Object verified -Sum).Sum+' verified'}else{'No task-fit evidence'}))));[void]$panel.Children.Add($card)}
 [void]$panel.Children.Add((New-BunnyCaption 'Scores are not success probabilities. Choose an eligible agent above.'));$panel.Visibility='Visible'
}
function Set-BunnyOrb([string]$State) {
 if($State-eq$bunnyOrbState){return};$script:bunnyOrbState=$State
 $halo=$bunnyControls.OrbHalo;$halo.BeginAnimation([Windows.UIElement]::OpacityProperty,$null);$halo.RenderTransform.BeginAnimation([Windows.Media.RotateTransform]::AngleProperty,$null);$halo.Opacity=0.22
 $ink=switch($State){'waiting'{'BunnyWarning'}'failed'{'BunnyNegative'}'completed'{'BunnyPositive'}'offline'{'BunnyMuted'}'routing'{'BunnyViolet'}default{'BunnyAccent'}}
 Set-BunnyRef $halo ([Windows.Shapes.Shape]::StrokeProperty) $ink
 $bunnyControls.BrandMark.Opacity=if($State-eq'completed'){0.16}else{1};$bunnyControls.OrbCheck.Visibility=if($State-eq'completed'){'Visible'}else{'Collapsed'}
 $bunnyControls.OrbRoot.Opacity=if($State-eq'offline'){0.45}else{1}
 [Windows.Automation.AutomationProperties]::SetName($bunnyControls.BunnyButton,('Bunny '+$State+'. Click to compose; hold for voice.'))
 if(-not$bunnyAnimate){return}
 if($State-eq'routing'){$rotate=[Windows.Media.Animation.DoubleAnimation]::new(0,360,[Windows.Duration]::new([TimeSpan]::FromMilliseconds($bunnyMotion.route*3)));$rotate.RepeatBehavior=[Windows.Media.Animation.RepeatBehavior]::Forever;$halo.RenderTransform.BeginAnimation([Windows.Media.RotateTransform]::AngleProperty,$rotate)}
 if($State-in@('working','waiting','failed','completed')){$duration=if($State-eq'working'){$bunnyMotion.breath}elseif($State-eq'completed'){$bunnyMotion.success}else{$bunnyMotion.warning};$pulse=[Windows.Media.Animation.DoubleAnimation]::new(0.15,0.65,[Windows.Duration]::new([TimeSpan]::FromMilliseconds($duration)));$pulse.AutoReverse=$true;$pulse.RepeatBehavior=if($State-eq'failed'){[Windows.Media.Animation.RepeatBehavior]::new(2)}elseif($State-eq'completed'){[Windows.Media.Animation.RepeatBehavior]::new(1)}else{[Windows.Media.Animation.RepeatBehavior]::Forever};$halo.BeginAnimation([Windows.UIElement]::OpacityProperty,$pulse)}
}
function Update-BunnyMotion {
 Set-BunnyMotionMode
 $task=@($bunnySnapshot.tasks|Where-Object id -eq $bunnySelectedId)|Select-Object -First 1
 $state=if(-not$bunnyOnline){'offline'}elseif($bunnyView-eq'routing'){'routing'}elseif(-not$task-or($bunnyView-eq'idle'-and$task.state-in@('completed','failed','stopped'))){'idle'}elseif($task.state-in@('waiting_for_approval','waiting_for_input','waiting_for_agent_approval','paused','queued')){'waiting'}elseif($task.state-in@('completed','failed')){$task.state}elseif($task.state-eq'stopped'){'idle'}else{'working'}
 if(-not$bunnyAnimate-and$bunnyOrbState){$bunnyControls.OrbHalo.BeginAnimation([Windows.UIElement]::OpacityProperty,$null);$bunnyControls.OrbHalo.RenderTransform.BeginAnimation([Windows.Media.RotateTransform]::AngleProperty,$null)}
 Set-BunnyOrb $state
 if($bunnyView-eq'routing'){Draw-BunnyRoute $bunnyControls.RouteMap $null}
 if($bunnyView-eq'constellation'){Draw-BunnyConstellation}
 if($bunnyHot){Set-BunnyRef $bunnyControls.ThermalValue ([Windows.Controls.TextBlock]::ForegroundProperty) 'BunnyWarning';if($bunnyAnimate-and$bunnyThermalMotionKey-ne$bunnyHot.key){$pulse=[Windows.Media.Animation.DoubleAnimation]::new(.6,1,[Windows.Duration]::new([TimeSpan]::FromMilliseconds($bunnyMotion.warning)));$pulse.AutoReverse=$true;$pulse.RepeatBehavior=[Windows.Media.Animation.RepeatBehavior]::new(2);$bunnyControls.ThermalValue.BeginAnimation([Windows.UIElement]::OpacityProperty,$pulse)};$script:bunnyThermalMotionKey=$bunnyHot.key}else{$script:bunnyThermalMotionKey=$null};if(-not$bunnyAnimate){$bunnyControls.ThermalValue.BeginAnimation([Windows.UIElement]::OpacityProperty,$null)}
}
function Draw-BunnyJourney($Task) {
 $bunnyControls.Journey.Children.Clear();$started=$null-ne$Task.startedAt;$terminal=$Task.state-in@('completed','failed','stopped')
 $steps=@(@('Prompt','done'),@('Route','done'),@('Approve',$(if($started){'done'}elseif($Task.state-eq'waiting_for_approval'){'current'}else{'next'})),@('Work',$(if($started){if($terminal-or$Task.state-eq'verifying'){'done'}else{'current'}}else{'next'})),@('Verify',$(if($Task.verification){if($Task.verification.passed){'done'}else{'failed'}}elseif($Task.state-eq'verifying'){'current'}elseif($terminal){'unavailable'}else{'next'})),@($(if($Task.state-eq'failed'){'Failed'}elseif($Task.state-eq'stopped'){'Stopped'}else{'Complete'}),$(if($Task.state-eq'completed'){'done'}elseif($Task.state-eq'failed'){'failed'}else{'next'})))
 foreach($step in $steps){$stack=[Windows.Controls.StackPanel]::new();$stack.Width=($bunnyWindow.Width-72)/6;$stack.HorizontalAlignment='Center';$dot=[Windows.Controls.TextBlock]::new();$dot.Text=switch($step[1]){'done'{[string][char]0x2713}'current'{[string][char]0x25CF}'failed'{[string][char]0x00D7}default{[string][char]0x25CB}};$dot.HorizontalAlignment='Center';$ink=switch($step[1]){'done'{'BunnyPositive'}'current'{'BunnyAccent'}'failed'{'BunnyNegative'}default{'BunnyMuted'}};Set-BunnyRef $dot ([Windows.Controls.TextBlock]::ForegroundProperty) $ink;$caption=New-BunnyCaption $step[0] $ink;$caption.HorizontalAlignment='Center';$stack.ToolTip=$step[0]+': '+$step[1];[void]$stack.Children.Add($dot);[void]$stack.Children.Add($caption);[void]$bunnyControls.Journey.Children.Add($stack)}
 $events=@($bunnySnapshot.events|Where-Object {$_.taskId-eq$Task.id-and$_.type-in@('agent.reading','agent.editing','agent.command','agent.testing','agent.rendering','agent.building','agent.searching','agent.verifying')}|Select-Object -Last 3)
 $bunnyControls.ActivityRibbon.Visibility=if($events.Count){'Visible'}else{'Collapsed'};$bunnyControls.ActivityRibbon.Content=(@($events|ForEach-Object {$_.type.Replace('agent.','').ToUpper()+' '+$_.detail})-join(' '+[char]0x2192+' '));$bunnyControls.ActivityRibbon.ToolTip=$bunnyControls.ActivityRibbon.Content
 if($Task.latestEvent.type-match'thinking|reasoning'){$bunnyControls.TaskDetail.Text='Working...';$bunnyControls.TaskDetail.ToolTip='Provider is working.';$bunnyControls.CompactActivity.Text='Working...'}
 if($Task.state-eq'waiting_for_approval'){Draw-BunnyRoute $bunnyControls.ApprovalRouteMap $Task}
}
function Add-BunnyMapOrb($Canvas,[double]$X,[double]$Y) {
 $orb=[Windows.Controls.Border]::new();$orb.Width=54;$orb.Height=54;$orb.CornerRadius=[Windows.CornerRadius]::new(27);$orb.BorderThickness=[Windows.Thickness]::new(1);Set-BunnyRef $orb ([Windows.Controls.Border]::BorderBrushProperty) 'BunnyAccent';Set-BunnyRef $orb ([Windows.Controls.Border]::BackgroundProperty) 'BunnyAccentSoft'
 $mark=[Windows.Shapes.Path]::new();$mark.Data=$bunnyControls.BrandMark.Data;$mark.Width=25;$mark.Height=34;$mark.Stretch='Uniform';$mark.HorizontalAlignment='Center';$mark.VerticalAlignment='Center';Set-BunnyRef $mark ([Windows.Shapes.Shape]::FillProperty) 'BunnyText';$orb.Child=$mark;[Windows.Controls.Canvas]::SetLeft($orb,$X-27);[Windows.Controls.Canvas]::SetTop($orb,$Y-27);[void]$Canvas.Children.Add($orb)
}
function Set-BunnyAssignmentFlow($Line) {
 if(-not$bunnyAnimate){return}
 $Line.StrokeDashArray=[Windows.Media.DoubleCollection]::new();$Line.StrokeDashArray.Add(4);$Line.StrokeDashArray.Add(2)
 $flow=[Windows.Media.Animation.DoubleAnimation]::new(0,-6,[Windows.Duration]::new([TimeSpan]::FromMilliseconds($bunnyMotion.route)))
 $flow.RepeatBehavior=[Windows.Media.Animation.RepeatBehavior]::Forever
 $Line.BeginAnimation([Windows.Shapes.Shape]::StrokeDashOffsetProperty,$flow)
}
function Draw-BunnyRoute($Canvas,$Task) {
 $Canvas.Children.Clear();$width=[Math]::Max(260,$bunnyWindow.Width-76);$Canvas.Width=$width;$Canvas.Height=210;$cx=$width/2;$cy=130;$scores=@($Task.decision.scores|Where-Object {$null-ne$_.score});$min=if($scores.Count){($scores|Measure-Object score -Minimum).Minimum}else{0};$max=if($scores.Count){($scores|Measure-Object score -Maximum).Maximum}else{0}
 $nodes=@(@('codex',44,130),@('claude',$cx,32),@('ollama',($width-44),130))
 foreach($node in $nodes){$id=$node[0];$score=@($scores|Where-Object provider -eq $id)|Select-Object -First 1;$strength=if($score){if($max-eq$min){1}else{([double]$score.score-$min)/($max-$min)}}else{0};$line=[Windows.Shapes.Line]::new();$line.X1=$cx;$line.Y1=$cy;$line.X2=$node[1];$line.Y2=$node[2];$line.StrokeThickness=1+$strength*2;$line.Opacity=if($Task.provider-eq$id){0.85}else{0.16+$strength*0.25};Set-BunnyRef $line ([Windows.Shapes.Shape]::StrokeProperty) $(if($id-eq'claude'){'BunnyClaude'}else{'BunnyAccent'});[void]$Canvas.Children.Add($line)
  if(-not$Task){Set-BunnyAssignmentFlow $line}
  $stack=[Windows.Controls.StackPanel]::new();$stack.Width=86;$tile=New-BunnyTile $id 30;$tile.HorizontalAlignment='Center';[void]$stack.Children.Add($tile);$label=New-BunnyCaption $(if($id-eq'claude'){'Claude'}else{Get-BunnyProviderName $id}) 'BunnyText';$label.HorizontalAlignment='Center';[void]$stack.Children.Add($label);$value=New-BunnyCaption $(if($score){'Score '+([double]$score.score).ToString('0.00')}elseif($Task){'Not scored'}else{'Scores pending'});$value.HorizontalAlignment='Center';[void]$stack.Children.Add($value);[Windows.Controls.Canvas]::SetLeft($stack,[double]$node[1]-43);[Windows.Controls.Canvas]::SetTop($stack,[double]$node[2]-20);[void]$Canvas.Children.Add($stack)
 };Add-BunnyMapOrb $Canvas $cx $cy
}
function Draw-BunnyConstellation {
 $canvas=$bunnyControls.ConstellationMap;$canvas.Children.Clear();$width=[Math]::Max(260,$bunnyWindow.Width-76);$canvas.Width=$width;$canvas.Height=340;$cx=$width/2;$cy=170;$active=@($bunnySnapshot.tasks|Where-Object state -notin @('completed','failed','stopped')|Select-Object -First 6)
 for($i=0;$i-lt$active.Count;$i++){$task=$active[$i];$angle=($i*360/[Math]::Max(3,$active.Count)-90)*[Math]::PI/180;$x=$cx+[Math]::Cos($angle)*$width*.33;$y=$cy+[Math]::Sin($angle)*112;$line=[Windows.Shapes.Line]::new();$line.X1=$cx;$line.Y1=$cy;$line.X2=$x;$line.Y2=$y;$line.StrokeThickness=1;$line.Opacity=0.4;Set-BunnyRef $line ([Windows.Shapes.Shape]::StrokeProperty) 'BunnyAccent';if($task.state-in@('launching','running','verifying')){Set-BunnyAssignmentFlow $line};[void]$canvas.Children.Add($line);$button=[Windows.Controls.Button]::new();$button.Width=120;$button.Tag=$task.id;$button.Padding='8';$stack=[Windows.Controls.StackPanel]::new();$tile=New-BunnyTile $task.provider 26;$tile.HorizontalAlignment='Center';[void]$stack.Children.Add($tile);$label=New-BunnyCaption (Get-BunnyProviderName $task.provider) 'BunnyText';$label.HorizontalAlignment='Center';[void]$stack.Children.Add($label);$title=New-BunnyCaption $task.title;$title.TextTrimming='CharacterEllipsis';$title.TextWrapping='NoWrap';[void]$stack.Children.Add($title);$button.Content=$stack;$button.Add_Click({$script:bunnySelectedId=$this.Tag;Expand-Bunny});[Windows.Controls.Canvas]::SetLeft($button,$x-60);[Windows.Controls.Canvas]::SetTop($button,$y-30);[void]$canvas.Children.Add($button)};Add-BunnyMapOrb $canvas $cx $cy
 $bunnyControls.ConstellationNote.Text=if($active.Count){[string]$active.Count+' active assignments. Handoff records unavailable.'}else{'No active assignments. Handoff records unavailable.'}
}

# Reuse the same Island surface; no new top-level windows.
$orbRoot=[Windows.Controls.Grid]::new();$orbRoot.Width=36;$orbRoot.Height=36;$bunnyControls.BunnyButton.Content=$null;$bunnyControls.BrandTile.CornerRadius=[Windows.CornerRadius]::new(14);[void]$orbRoot.Children.Add($bunnyControls.BrandTile)
$halo=[Windows.Shapes.Ellipse]::new();$halo.Width=34;$halo.Height=34;$halo.StrokeThickness=1;$halo.StrokeDashArray=[Windows.Media.DoubleCollection]::new();$halo.StrokeDashArray.Add(8);$halo.StrokeDashArray.Add(3);$halo.RenderTransform=[Windows.Media.RotateTransform]::new();$halo.RenderTransformOrigin=[Windows.Point]::new(.5,.5);[void]$orbRoot.Children.Add($halo)
$check=New-BunnyIcon 'check' 15;Set-BunnyRef $check.Tag ([Windows.Shapes.Shape]::StrokeProperty) 'BunnyPositive';$check.HorizontalAlignment='Center';$check.VerticalAlignment='Center';$check.Visibility='Collapsed';[void]$orbRoot.Children.Add($check);$bunnyControls.BunnyButton.Content=$orbRoot;$bunnyControls.OrbRoot=$orbRoot;$bunnyControls.OrbHalo=$halo;$bunnyControls.OrbCheck=$check
$shortcuts=[Windows.Controls.WrapPanel]::new();$shortcuts.Margin='0,12,0,0';foreach($shortcut in @(@('Deep Research','Research ','deep'),@('Create PDF','Create a PDF report about ','balanced'),@('Build Website','Build a website for ','balanced'))){$button=[Windows.Controls.Button]::new();$button.Content=$shortcut[0];$button.Tag=$shortcut;$button.FontSize=11;$button.Margin='0,0,4,0';$button.Add_Click({$bunnyControls.Prompt.Text=$this.Tag[1];$bunnyControls.Mode.SelectedIndex=if($this.Tag[2]-eq'deep'){2}else{1};$bunnyControls.Prompt.Focus()|Out-Null});[void]$shortcuts.Children.Add($button)};$bunnyControls.ComposerPanel.Children.Insert(2,$shortcuts)
$voiceButton=[Windows.Controls.Button]::new();$voiceButton.Content='Voice';$voiceButton.FontSize=11;$voiceButton.Add_Click({Set-BunnyView 'voice'});[void]$shortcuts.Children.Add($voiceButton)
$routeMap=[Windows.Controls.Canvas]::new();$bunnyControls.RouteMap=$routeMap;$bunnyControls.RoutingPanel.Children.Insert(0,$routeMap)
$approvalMap=[Windows.Controls.Canvas]::new();$bunnyControls.ApprovalRouteMap=$approvalMap;$routeExpander=@($bunnyControls.ApprovalPanel.Children|Where-Object {$_-is[Windows.Controls.Expander]})|Select-Object -First 1;$routeExpander.Content.Children.Insert(0,$approvalMap)
$comparison=[Windows.Controls.StackPanel]::new();$comparison.Visibility='Collapsed';$bunnyControls.ProviderComparison=$comparison;$bunnyControls.ApprovalPanel.Children.Insert(($bunnyControls.ApprovalPanel.Children.Count-2),$comparison);$bunnyControls.ChangeButton.Add_Click({Draw-BunnyComparison})
$journey=[Windows.Controls.StackPanel]::new();$journey.Orientation='Horizontal';$journey.Margin='0,8,0,16';$bunnyControls.Journey=$journey;$bunnyControls.TaskPanel.Children.Insert(3,$journey)
$ribbon=[Windows.Controls.Button]::new();$ribbon.HorizontalContentAlignment='Right';$ribbon.FontSize=10;$ribbon.MaxHeight=44;$ribbon.Visibility='Collapsed';$ribbon.Add_Click({Open-BunnyApplication $bunnySelectedId});$bunnyControls.ActivityRibbon=$ribbon;$bunnyControls.TaskPanel.Children.Insert(7,$ribbon)
$constellation=[Windows.Controls.StackPanel]::new();$constellation.Visibility='Collapsed';$heading=New-BunnyCaption 'CONSTELLATION' 'BunnyText';[void]$constellation.Children.Add($heading);$map=[Windows.Controls.Canvas]::new();[void]$constellation.Children.Add($map);$note=New-BunnyCaption '';[void]$constellation.Children.Add($note);$bunnyControls.ConstellationPanel=$constellation;$bunnyControls.ConstellationMap=$map;$bunnyControls.ConstellationNote=$note;$bunnyControls.Details.Children.Insert(1,$constellation)
$constellationButton=[Windows.Controls.Button]::new();$constellationButton.Content='Constellation';$constellationButton.HorizontalContentAlignment='Left';$constellationButton.Add_Click({Draw-BunnyConstellation;Set-BunnyView 'constellation'});$bunnyControls.MenuPanel.Children.Insert(2,$constellationButton)
$voicePanel=[Windows.Controls.StackPanel]::new();$voicePanel.Visibility='Collapsed';$title=New-BunnyCaption 'Voice input unavailable' 'BunnyText';$title.FontSize=21;[void]$voicePanel.Children.Add($title);$detail=New-BunnyCaption 'This native Island has no speech-service attachment. Use Voice in the application composer, or type your task here. Both use the same routing and approval.';$detail.Margin='0,16,0,16';[void]$voicePanel.Children.Add($detail);$return=[Windows.Controls.Button]::new();$return.Content='Type a task';$return.Add_Click({Set-BunnyView 'composer';$bunnyControls.Prompt.Focus()|Out-Null});[void]$voicePanel.Children.Add($return);$bunnyControls.NativeVoicePanel=$voicePanel;$bunnyControls.Details.Children.Insert(1,$voicePanel)
$motionLabel=New-BunnyCaption 'Motion';$motionChoice=[Windows.Controls.ComboBox]::new();$motionChoice.Margin='0,4,0,12';$bunnyControls.MotionChoice=$motionChoice;$settingsStack=$bunnyControls.ThemeChoice.Parent;$settingsStack.Children.Insert(12,$motionLabel);$settingsStack.Children.Insert(13,$motionChoice)
Add-BunnyChoice $motionChoice @(@('full','Full'),@('reduced','Reduced'),@('off','Off')) 'motion'
$hold=[Windows.Threading.DispatcherTimer]::new();$hold.Interval=[TimeSpan]::FromMilliseconds(420);$hold.Add_Tick({$hold.Stop();$script:bunnyHeld=$true;Set-BunnyView 'voice'});$bunnyControls.BunnyButton.Add_PreviewMouseLeftButtonDown({$script:bunnyHeld=$false;$hold.Start()});$bunnyControls.BunnyButton.Add_PreviewMouseLeftButtonUp({$hold.Stop();if($bunnyHeld){$_.Handled=$true}});$bunnyControls.BunnyButton.Add_MouseLeave({$hold.Stop()});$bunnyWindow.Add_Closed({$hold.Stop()})
